language: php

sudo: false

php:
  - 5.5
  - 5.6
  - hhvm
  - 7

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

matrix:
  allow_failures:
    - php: hhvm
    - php: 7
  fast_finish: true
