language: php

sudo: false

php:
  - 7
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

matrix:
  allow_failures:
    - php: 7
  fast_finish: true
